# Generated by Django 5.0.1 on 2024-06-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Meta_Dashboard",
            fields=[
                (
                    "Pending_id",
                    models.BigAutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("scan_id", models.IntegerField(blank=True, null=True)),
                ("Ip", models.GenericIPAddressField()),
                ("Send_status", models.BooleanField(default=False)),
                ("Meta_id", models.IntegerField(blank=True, null=True)),
                ("Meta_start_time", models.DateTimeField(blank=True, null=True)),
                ("Meta_stop_time", models.DateTimeField(blank=True, null=True)),
                (
                    "Meta_scan_status",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
            ],
            options={
                "ordering": ["Pending_id"],
            },
        ),
    ]
