# Generated by Django 5.0.1 on 2024-06-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Nmap_Core_Dashboard",
            fields=[
                (
                    "Scan_id",
                    models.BigAutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("ip", models.GenericIPAddressField()),
                ("ip_type", models.CharField(blank=True, max_length=128, null=True)),
                ("pt_start_time", models.DateTimeField(blank=True, null=True)),
                ("pt_stop_time", models.DateTimeField(blank=True, null=True)),
                ("etc", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "current_status",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
            ],
            options={
                "ordering": ["Scan_id"],
            },
        ),
    ]
