# Generated by Django 5.0.1 on 2024-06-18 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_host_scan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scan",
            name="host",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.RESTRICT, to="base.host"
            ),
            preserve_default=False,
        ),
    ]
