# Generated by Django 5.0.1 on 2024-07-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_pt_age_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="privileges",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
