# Generated by Django 5.0.1 on 2024-07-16 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_alter_users_privileges"),
    ]

    operations = [
        migrations.RenameField(
            model_name="users",
            old_name="active_status",
            new_name="permission_Staff_status",
        ),
        migrations.RenameField(
            model_name="users",
            old_name="staff_status",
            new_name="permission_Superuser_status",
        ),
        migrations.RenameField(
            model_name="users",
            old_name="superuser_status",
            new_name="permission_active_status",
        ),
        migrations.RenameField(
            model_name="users",
            old_name="privileges",
            new_name="privilege",
        ),
    ]
