# Generated by Django 5.0.1 on 2024-07-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_rename_active_status_users_permission_staff_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="privilege",
            field=models.JSONField(blank=True, max_length=256, null=True),
        ),
    ]
