# Generated by Django 5.0.1 on 2024-09-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_alter_users_privilege"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Users",
        ),
        migrations.AlterField(
            model_name="meta_dashboard",
            name="scan_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
