# Generated by Django 5.0.1 on 2024-09-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_delete_users_alter_meta_dashboard_scan_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meta_dashboard",
            name="scan_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
