from django.contrib import admin
from django.urls import path,include
from .views import generate_captcha,callwithoutcp,call,user_delete,get_chart_weekly,get_chart_monthly,validate,get_nmap,get_meta,get_scan,get_host,get_pending_meta,get_meta_host,get_meta_service,get_meta_vulnerability,get_meta_scan,check_login,add_user,send_csv,send_users,get_nmap_by_id,update_scan,add_Scan,get_meta_id,update_meta_id,VA_chartAPI, asset_summary,addMeta,delete_multiple_scan,addscantable,addhosttable,addPendingMeta,addMeta_Scan,addMeta_Host,addMeta_Service,addMeta_Vulterability,update_meta_id,get_scan_by_id,get_host_by_id,get_metascan_by_id,get_metahost_by_id,get_metaservice_by_id,get_metavulnerability_by_id,update_scantable_id,update_hosttable_id,update_pendingmeta_id,update_metascantable_id,update_metahosttable_id,update_metaservicetable_id,update_metavulenrabilitytable_id,delete_multiple_meta,delete_multiple_scan_table,delete_multiple_host_table,delete_multiple_metascan_table,delete_multiple_pendingmeta_table,delete_multiple_metashost_table,delete_multiple_metaservice_table,delete_multiple_metavulnerability_table,get_pendingmeta_id




# urls to be changed='/analytics'
urlpatterns = [
    path("nmap/", get_nmap ,name="get_nmap"),
    path("meta/",get_meta,name="get_meta"),
    path("scan/",get_scan,name="get_scan"),
    path("host/",get_host,name="get_host"),
    path("pendingmeta/",get_pending_meta,name="get_pending_meta"),
    path("meta_scan/",get_meta_scan,name="get_meta_scan"),
    path("meta_host/",get_meta_host,name="get_meta_host"),
    path("meta_service/",get_meta_service,name="get_meta_service"),
    path("meta_vulnerability/",get_meta_vulnerability,name="get_meta_vulnerability"),
    path('nmap/<int:id>',get_nmap_by_id,name="get_nmap_by_id"),
    path('getmeta/<int:id>',get_meta_id,name="get_meta_id"),
    path('getscan/<int:id>',get_scan_by_id,name="get_scan_by_id"),
    path('gethost/<str:id>',get_host_by_id,name="get_host_by_id"),
    path('getpendingmeta/<int:id>',get_pendingmeta_id,name="get_pendingmeta_id"),
    path('getmetascan/<int:id>',get_metascan_by_id,name="get_metascan_by_id"),
    path('getmetahost/<int:id>',get_metahost_by_id,name="get_metahost_by_id"),
    path('getmetaservice/<int:id>',get_metaservice_by_id,name="get_metaservice_by_id"),
    path('getmetavulnerability/<int:id>',get_metavulnerability_by_id,name="get_metavulnerability_by_id"),
    path("checkLogin/",check_login,name="check_login"),
    path('validate/',validate),
    path("addUser/",add_user,name="addUser/"),
    path("sendCSV/",send_csv,name="sendCSV"),
    path('getuser/',send_users,name="getuser"),
    path('addScan/',add_Scan,name="add_scan"),
    path('addMeta/',addMeta,name='add_meta'),
    path('addscantable/',addscantable,name="addscantable"),
    path('addhosttable/',addhosttable,name="addhosttable"),
    path('addPendingMeta/',addPendingMeta,name="addPendingMeta"),
    path('addMeta_Scan/',addMeta_Scan,name="add_meta_scan"),
    path('addMeta_Host/',addMeta_Host,name="add_meta_host"),
    path('addMeta_Service/',addMeta_Service,name="addMeta_Service"),
    path('addMeta_Vulterability/',addMeta_Vulterability,name="addMeta_Vulterability"),
    path('scanDelete/',delete_multiple_scan,name="delete_multiple_scan"),
    path('metaDelete/',delete_multiple_meta,name="delete_meta"),
    path('scantableDelete/',delete_multiple_scan_table,name="delete_multiple_scan_table"),
    path('hosttableDelete/',delete_multiple_host_table,name="delete_multiple_host_table"),
    path('pendingmetaDelete/',delete_multiple_pendingmeta_table,name="delete_multiple_pendingmeta_table"),
    path('metascantableDelete/',delete_multiple_metascan_table,name="delete_multiple_metascan_table"),
    path('metahosttableDelete/',delete_multiple_metashost_table,name="delete_multiple_metashost_table"),
    path('metaservicetableDelete/',delete_multiple_metaservice_table,name="delete_multiple_metaservice_table"),
    path('metavulnerabilitytableDelete/',delete_multiple_metavulnerability_table,name="delete_multiple_metavulnerability_table"),
    # path('metaDelete/<int:id>/',delete_meta_id,name='delete_meta_id'),
    path('scanUpdate/<int:id>/',update_scan,name="update_scan"),
    path('metaUpdate/<int:id>/',update_meta_id,name='update_meta_id'),
    path('scantableUpdate/<int:id>/',update_scantable_id,name='update_scantable_id'),
    path('hosttableUpdate/<str:id>/',update_hosttable_id,name='update_hosttable_id'),
    path('pendingmetaUpdate/<int:id>/',update_pendingmeta_id,name="update_pendingmeta_id"),
    path('metascantableUpdate/<int:id>/',update_metascantable_id,name='update_metascantable_id'),
    path('metahosttableUpdate/<int:id>/',update_metahosttable_id,name='update_metahosttable_id'),
    path('metaservicetableUpdate/<int:id>/',update_metaservicetable_id,name='update_metaservicetable_id'),
    path('metavulnerabilitytableUpdate/<int:id>/',update_metavulenrabilitytable_id,name='update_metavulenrabilitytable_id'),
    path('va_chartAPI/',VA_chartAPI,name="va_chartAPI"),
    path('asset_summary',call, name="asset_summary"),
    path('assestwithoutcp',callwithoutcp),
    path('chartdatamonthly/',get_chart_monthly),
    path('chartdataweekly/',get_chart_weekly),
    path('deleteuser/',user_delete),
    path('generate-captcha/',generate_captcha),
]
